# Generated by Django 5.2.3 on 2025-06-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_copy',
            field=models.FileField(blank=True, null=True, upload_to='books/'),
        ),
    ]
