# Generated by Django 5.2.3 on 2025-06-28 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_pdf_copy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pdf_copy',
        ),
    ]
